# SELECT
# *
# FROM
# OFFLINE_SALE

SELECT
PRODUCT_CODE,
SUM(SALES_AMOUNT) * PRICE AS SALES
FROM
PRODUCT
LEFT JOIN OFFLINE_SALE
ON PRODUCT.PRODUCT_ID = OFFLINE_SALE.PRODUCT_ID
GROUP BY OFFLINE_SALE.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE ASC