SELECT
    ANIMAL_OUTS.ANIMAL_ID
    , ANIMAL_OUTS.NAME
FROM
    ANIMAL_OUTS
JOIN
   ANIMAL_INS
   ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
ORDER BY TIMESTAMPDIFF(DAY, ANIMAL_INS.DATETIME, ANIMAL_OUTS.DATETIME) DESC
LIMIT 2