# select
# *
# from
# ONLINE_SALE
SELECT
YEAR(ONLINE_SALE.SALES_DATE) AS YEAR
, MONTH(ONLINE_SALE.SALES_DATE) AS MONTH
, USER_INFO.GENDER
, COUNT(DISTINCT ONLINE_SALE.USER_ID) AS USERS
FROM
ONLINE_SALE
INNER JOIN
USER_INFO
ON USER_INFO.USER_ID = ONLINE_SALE.USER_ID
WHERE
NOT ISNULL(USER_INFO.GENDER)
GROUP BY
YEAR, MONTH, USER_INFO.GENDER
ORDER BY
YEAR ASC, MONTH ASC, USER_INFO.GENDER ASC