# SELECT
#     DURATION_TYPE
#     , DISCOUNT_RATE
# FROM
#     CAR_RENTAL_COMPANY_DISCOUNT_PLAN
# WHERE
#     CAR_TYPE LIKE "트럭"
    
SELECT
    HISTORY_ID
    , round(DAILY_FEE * (DATEDIFF(CAR_RENTAL_COMPANY_RENTAL_HISTORY.END_DATE,CAR_RENTAL_COMPANY_RENTAL_HISTORY.START_DATE)+1)
    * (case 
    when DATEDIFF(END_DATE,START_DATE)+1 < 7 then 1
    when DATEDIFF(END_DATE,START_DATE)+1 < 30 then 0.95
    when DATEDIFF(END_DATE,START_DATE)+1 < 90 then 0.92
    else 0.85 end)) as "FEE"
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
JOIN
    CAR_RENTAL_COMPANY_CAR
    USING(CAR_ID)
WHERE
    CAR_RENTAL_COMPANY_CAR.CAR_TYPE LIKE "트럭"
group by HISTORY_ID

order by FEE desc , HISTORY_ID desc