SELECT
    A.APNT_NO
    , PATIENT.PT_NAME
    , A.PT_NO
    , A.MCDP_CD
    , DOCTOR.DR_NAME
    , A.APNT_YMD
FROM
    APPOINTMENT as A
JOIN
    DOCTOR
    ON DOCTOR.DR_ID = A.MDDR_ID
JOIN
    PATIENT
    ON PATIENT.PT_NO = A.PT_NO
WHERE
    A.MCDP_CD = "CS"
    AND A.APNT_CNCL_YN = "N"
    AND A.APNT_YMD LIKE "2022-04-13%"
ORDER BY
    APNT_YMD ASC