SELECT
DEVELOPERS.ID
, DEVELOPERS.EMAIL
, DEVELOPERS.FIRST_NAME
, DEVELOPERS.LAST_NAME
FROM
DEVELOPERS
WHERE
    DEVELOPERS.SKILL_CODE &     
    (
    SELECT
        SUM(CODE)
    FROM
        SKILLCODES
    WHERE
        CATEGORY = "Front End"
    GROUP BY
        CATEGORY
    )
ORDER BY
DEVELOPERS.ID ASC