SELECT
USED_GOODS_USER.USER_ID
, USED_GOODS_USER.NICKNAME
, SUM(if(USED_GOODS_BOARD.STATUS = 'DONE', USED_GOODS_BOARD.PRICE, 0)) AS TOTAL_SALES
FROM
USED_GOODS_USER
    LEFT OUTER JOIN USED_GOODS_BOARD
    ON USED_GOODS_USER.USER_ID = USED_GOODS_BOARD.WRITER_ID
GROUP BY USED_GOODS_BOARD.WRITER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES

# SELECT
# *
# FROM
# USED_GOODS_BOARD