SELECT
    DISTINCT CAR_RENTAL_COMPANY_CAR.CAR_ID
FROM
    CAR_RENTAL_COMPANY_CAR
JOIN
    (
    SELECT
        CAR_ID
        , START_DATE
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE
        START_DATE LIKE "2022-10%"
    ) AS HISTORY
    ON HISTORY.CAR_ID = CAR_RENTAL_COMPANY_CAR.CAR_ID
WHERE
    CAR_RENTAL_COMPANY_CAR.CAR_TYPE = '세단'
ORDER BY
    CAR_RENTAL_COMPANY_CAR.CAR_ID DESC