# (SELECT
# BOARD_ID
# FROM
# USED_GOODS_BOARD
# ORDER BY VIEWS DESC)

SELECT
CONCAT('/home/grep/src/', USED_GOODS_FILE.BOARD_ID, '/', USED_GOODS_FILE.FILE_ID, USED_GOODS_FILE.FILE_NAME, USED_GOODS_FILE.FILE_EXT) AS FILE_PATH
FROM
USED_GOODS_BOARD
    LEFT OUTER JOIN USED_GOODS_FILE
    ON USED_GOODS_FILE.BOARD_ID=USED_GOODS_BOARD.BOARD_ID
WHERE
    USED_GOODS_BOARD.VIEWS = (SELECT MAX(USED_GOODS_BOARD.VIEWS) FROM USED_GOODS_BOARD)
ORDER BY USED_GOODS_FILE.FILE_ID DESC

# SELECT *
# FROM USED_GOODS_BOARD