SELECT
BOOK.CATEGORY,
SUM(SALES) AS TOTAL_SALES
FROM
BOOK
LEFT JOIN
    BOOK_SALES ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID 
    WHERE
    BOOK_SALES.SALES_DATE BETWEEN DATE('2022-01-01') AND DATE('2022-01-31')
GROUP BY
CATEGORY
ORDER BY
CATEGORY ASC